default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: react_redux_action_cable_chat_dev
  username: react_redux_action_cable_chat
  password:

test:
  <<: *default
  database: react_redux_action_cable_chat_test
  username: react_redux_action_cable_chat
  password:

production:
  <<: *default
  database: react_redux_action_cable_chat_prod
  username: react_redux_action_cable_chat_prod
  password: <%= Rails.application.secrets.production_database_password %>
